### ISSUE TITLE
Error in action.py ?

### ISSUE THREAD

**Issue by CharlesButcher** [thekoc/devonthink-search-launchbar#1]
This looks really useful, but LaunchBar gives the error" "Script is invalid".

When I run `action.py` from BBEdit I get the log below. Is that of any help?

>Traceback (most recent call last):
  File "/Users/charles/Library/Application Support/LaunchBar/Actions/Search DEVONthink 3.lbaction/Contents/Scripts/action.py", line 56, in <module>
    main()
  File "/Users/charles/Library/Application Support/LaunchBar/Actions/Search DEVONthink 3.lbaction/Contents/Scripts/action.py", line 24, in main
    argument = json.loads(sys.argv[1])
IndexError: list index out of range

macOS 10.14.6 and I don't know the first thing about Python. `which python3` gives `/Users/charles/.pyenv/shims/python3`.

**Comment by CharlesButcher** [comment]
Everything is working fine for me with a clean install of Big Sur (Python 2.7.16) and DT 3.5.2.
